# class_mapping.py

class_name_mapping = {
    "Apple___Apple_scab": "Apple plant with Scab",
    "Apple___Black_rot": "Apple plant with Black Rot",
    "Apple___Cedar_apple_rust": "Apple plant with Cedar apple rust",
    "Apple___healthy": "Apple plant which is healthy",
    "Background_without_leaves": "No plant clearly identified",
    "Blueberry___healthy": "Blueberry plant ehich is healthy",
    "Cherry___Powdery_mildew": "Cherry plant with Powdery mildew",
    "Cherry___healthy": "Cherry plant which is healthy",
    "Corn___Cercospora_leaf_spot Gray_leaf_spot": "Corn plant with Gray leaf spot",
    "Corn___Common_rust": "Corn plant with Common rust",
    "Corn___Northern_Leaf_Blight": "Corn plant with Northern Leaf Blight",
    "Corn___healthy": "Corn plant which is  healthy",
    "Grape___Black_rot": "Grape plant with Black rot",
    "Grape___Esca_(Black_Measles)": "Grape Esca plant with Black Measles",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Grape plant with Leaf blight (Isariopsis Leaf Spot)",
    "Grape___healthy": "Grape plant which is healthy",
    "Orange___Haunglongbing_(Citrus_greening)": "Orange plant with Haunglongbing (Citrus greening)",
    "Peach___Bacterial_spot": "Peach plant with Bacterial spot",
    "Peach___healthy": "Peach which is healthy",
    "Pepper,_bell___Bacterial_spot": "Bell Pepper plant with Bacterial spot",
    "Pepper,_bell___healthy": "Bell Pepper which is healthy",
    "Potato___Early_blight": "Potato plant with Early blight",
    "Potato___Late_blight": "Potato plant with Late blight",
    "Potato___healthy": "Potato plant which is healthy",
    "Raspberry___healthy": "Raspberry plant which is healthy",
    "Soybean___healthy": "Soybean plant which is healthy",
    "Squash___Powdery_mildew": "Squash plant with Powdery mildew",
    "Strawberry___Leaf_scorch": "Strawberry plant with Leaf scorch",
    "Strawberry___healthy": "Strawberry plant which is healthy",
    "Tomato___Bacterial_spot": "Tomato plant with Bacterial spot",
    "Tomato___Early_blight": "Tomato plant with Early blight",
    "Tomato___Late_blight": "Tomato plant with Late blight",
    "Tomato___Leaf_Mold": "Tomato plant with Leaf Mold",
    "Tomato___Septoria_leaf_spot": "Tomato plant with Septoria leaf spot",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Tomato plant with Spider mites (Two spotted spider mite)",
    "Tomato___Target_Spot ": "Tomato plant with Target Spot ",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Tomato plant with Tomato Yellow Leaf Curl Virus",
    "Tomato___Tomato_mosaic_virus": "Tomato plant with Tomato mosaic virus",
    "Tomato___healthy": "Tomato plant with healthy"
}
